static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"
admin:          "_env:ADMIN:mats@hoppinger.com"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

# database:
#   user:     "_env:PGUSER:lambda-benchmark"
#   password: "_env:PGPASS:lambda-benchmark"
#   host:     "_env:PGHOST:localhost"
#   port:     "_env:PGPORT:5432"
#   database: "_env:PGDATABASE:lambda-benchmark"
#   poolsize: "_env:PGPOOLSIZE:10"
database:
  user:     "_env:MYSQL_USER:lambda_benchmark"
  password: "_env:MYSQL_PASSWORD:lambda_benchmark"
  host:     "_env:MYSQL_HOST:localhost"
  port:     "_env:MYSQL_PORT:5432"
  database: "_env:MYSQL_DATABASE:lambda_benchmark"
  poolsize: "_env:MYSQL_POOLSIZE:10"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE
